name: CoperniFUS viewer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest] # TODO add ubuntu-latest, windows-latest, macos-latest
        python-version: ['3.12']

    steps:
        
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installing CoperniFUS
        run: python -m pip install -e .

      - name: Installing test dependencies
        run: pip install pytest pytest-qt

      # - name: Download test BrainGlobe atlas
      #   run: brainglobe install -a example_mouse_100um

      - name: Testing CoperniFUS
        run: pytest tests/test_viewer.py
